### ISSUE TITLE
The very beginning

### ISSUE THREAD

**Issue by flsrg** [flsrg/autism-manager#1]
Надо подумать:
1. Какие платформы будем поддерживать.
2. Какие технологии будем использовать.
3. Как будем шифровать.
4. Будем ли передавать на сервер или только хранить локально на клиенте.

**Comment by Sergeicchh** [comment]
Предлагаю:
1. Платформы:
    - Windows (KMM Java app)
    - Android (KMM apk)
2. Технологии:
    - KMM (Kotlin multiplarform mobile).
    - DB: Локальная база? Вроде Room multiplatform должны были уже дропнуть.
    - UI: Jetpack Compose.
    - API: Ktor (Retrofit, возможно, тут избыточен).
    - Server: 
        - Kotlin Java app 
        - API: Ktor
        - HTTP requests: nginx
        - DB: MySQL
3. Шифрование:
    - Как-нибудь, надо смотреть какие библиотеки поддерживаются в KMM.
    - Вот этот вопрос надо по изучать.
4. Будем ли передавать на сервер или только хранить локально на клиенте:
    - Предлагаю передавать на сервер, чтобы можно было с разных устройств иметь доступ к одной базе. ЭТО БАЗА.
    - Но появляются сложности:
        - Приложение сервера.
        - Аккаунт.
        - Хранить ли строки на сервере в зашифрованном виде, или шифровать сразу на клиенте?

Предлагаю для начала создать клентские приложения, с запасом на API сервера, а дальше уже будет виднее. Может дропнем эту идею.

**Comment by flsrg** [comment]
Чо, это самое, предложений замечаний нет, двигаемся дальше? Могу закрывать задачку?
